### PR TITLE
Production release: 08/11

### PR DESCRIPTION
**Pull request by fultonesser**

### CODE REVIEW

**Comment by snim2** [comment]
@dragon-dxw I notice there's a few breakpoints and print statements in the migrations here. Is that idiomatic in Wagtail?

**Comment by dragon-dxw** [comment]
The print statements I'm tempted to leave -- it's a fairly hairy migration, and I think the benefit of being able to diagnose what happened and where it was up to makes them worthwhile. It shouldn't be very noisy on a new database.

The breakpoint is garbage and will stop the migration and should be removed; very sorry about that.

This is a somewhat scary deploy -- we're making database level tweaks to a big pile of things -- so please leave a message in Slack when you push this to production so we can easily find when to rollback to if there's unforeseen problems. I'm confident it's performed well locally but who knows what mysteries lie in production...

[concerned that the migration might not have been run against staging with those breakpoints?]

**Comment by snim2** [comment]
@dragon-dxw many thanks for that. Matty is away right now and I don't have the rights to close this PR, but that's probably the next step. I'll let people know that we need to notify you about the next release.

**Comment by dragon-dxw** [comment]
I've updated https://github.com/nhsx/nhsx-website/pull/743 so that it now passes CI (and also updates a bunch of dependencies.) I think that's worth merging and checking everything on staging remains happy.

**Pull request closed without merging**
