### PR TITLE
Use Draftail editor

### PR DESCRIPTION
**Pull request by mec**
Use the new Draftail editor not the deprecated 'Hallo' one see:

 https://docs.wagtail.io/en/v2.9.3/advanced_topics/customisation/extending_hallo.html?highlight=Hallo

### CODE REVIEW

**Comment by mec** [comment]
@pezholio have a look at this and let me know what you think - the Hallo editor is deprecated and the Draftail one is doing stuff they would like to use.

I can't see a reason not to do this and have passed the test suite locally with this change and check things look okay, but I have no existing content to check with.

Does merging this into the dev branch (dev?!?!?) deploy to a staging env?

**Comment by pezholio** [comment]
Just pulled it down and it looks good to me. I had no idea about this, so thanks for looking!

**Comment by pezholio** [comment]
And yeah, merging into dev will deploy to staging (https://web.staging.nhsx-website.dalmatian.dxw.net/)

**Comment by mec** [comment]
@pezholio nice one! I'll open this then if you feel like approving!

**Review by pezholio — APPROVED** [review]

**Comment by pezholio** [comment]
Done! 👍

**Pull request merged**
